call pathogen#infect()
syntax enable
filetype plugin on
set term=xterm-256color
set number
let g:go_disable_autoinstall=0
" Highlight
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:neocomplete#enable_at_startup = 1
:set mouse=nicr
:set mouse=a
colorscheme solarized
map <C-n> :NERDTreeToggle<CR>
let NERDTreeMapOpenInTab='\r'
:set backspace=indent,eol,start
set clipboard=unnamed
set noswapfile
let g:go_fmt_command = "goimports"
