call plug#begin()
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
call plug#end()
syntax enable
filetype plugin on
set term=xterm-256color
set number
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
:set mouse=nicr
:set mouse=a
:set backspace=indent,eol,start
set clipboard=unnamed
set noswapfile
